version: '3'
services:
  datanode-0:
    image: $IMAGE_REPO:$IMAGE_TAG
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://192.168.14.1:8020
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_webhdfs_enabled=1
    volumes:
      - data-0:/hadoop/dfs
    command:
      - datanode
    network_mode: "host"

volumes:
  data-0:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /sandbox/hdfs/datanode
