version: '3'
services:
  namenode:
    image: $IMAGE_REPO:$IMAGE_TAG_RASPI
    environment:
      - HDFS_CONF_dfs_webhdfs_enabled=1
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_permissions_enabled=false
    volumes:
      - name:/hadoop/dfs
    command:
      - namenode
    network_mode: "host"

  datanode-0:
    image: $IMAGE_REPO:$IMAGE_TAG_RASPI
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://0.0.0.0:8020
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_webhdfs_enabled=1
    volumes:
      - data-0:/hadoop/dfs
    command:
      - datanode
    network_mode: "host"

volumes:
  data-0:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /sandbox/hdfs/datanode
      
  name:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /sandbox/hdfs/namenode
